name: AnimalAbilities
main: com.animalabilities.AnimalAbilities
version: 1.0.0
api-version: 1.21
author: ChatGPT
description: Adds animal abilities and passives with GUI selection and cooldowns
commands:
  chooseanimal:
    description: Opens the animal selection menu
    usage: /chooseanimal
    permission: animalabilities.use
  resetanimal:
    description: Resets a player's chosen animal
    usage: /resetanimal <player|@a>
    permission: animalabilities.reset
permissions:
  animalabilities.use:
    description: Allows players to choose and use an animal
    default: true
  animalabilities.reset:
    description: Allows resetting other players’ animals
    default: op
