name: AnimalAbilities
version: 1.0
main: com.animalabilities.AnimalAbilities
api-version: 1.21
commands:
  chooseanimal:
    description: Opens the animal chooser GUI.
  resetanimal:
    description: Reset a player's animal (OP only).
  pounce:
    description: Wolf ability (Pounce).
  agilesprint:
    description: Cat ability (Agile Sprint).
  flutterfly:
    description: Bee ability (Flutter Fly).
  fastescape:
    description: Fox ability (Fast Escape).
  woolguard:
    description: Sheep ability (Wool Guard).
  fastgallop:
    description: Horse ability (Fast Gallop).
