# File: src/main/resources/plugin.yml
name: AnimalAbilities
main: com.animalabilities.AnimalAbilities
version: 1.0.0
api-version: 1.21
commands:
  chooseanimal:
    description: Open the animal chooser GUI
  resetanimal:
    description: Reset a player's animal (OP only or console)
  pounce:
    description: Wolf ability
  focus:
    description: Cat ability
  hover:
    description: Bee ability
  escape:
    description: Fox ability
  harden:
    description: Turtle ability
  gallop:
    description: Horse ability
  soften:
    description: Sheep ability
  sting:
    description: Ant ability
  glide:
    description: Owl ability
  discovery:
    description: Copper Golem ability
