name: AnimalAbilities
version: 1.0
main: com.animalabilities.AnimalAbilities
api-version: 1.21
commands:
  chooseanimal:
    description: Opens the animal selection menu.
  resetanimal:
    description: Resets a player's animal choice (OP only).
  pounce:
    description: Wolf ability.
  agilesprint:
    description: Cat ability.
  flutterfly:
    description: Bee ability.
  fastescape:
    description: Fox ability.
  woolguard:
    description: Sheep ability.
  fastgallop:
    description: Horse ability.
