name: Build AnimalAbilities Plugin

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Verify pom.xml exists
        run: |
          if [ ! -f pom.xml ]; then
            echo "❌ pom.xml not found in root directory!"
            exit 1
          fi

      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: AnimalAbilities
          path: target/*.jar
